### PR TITLE
Fixes #14: Changed links to GCI'18 Repository

### LINKED ISSUE #14: Redirect repository links to GCI'18 Website
Currently taking to the 2017 website, need to change to 2018 website. 

I'm working on it!

### PR DESCRIPTION
**Pull request by saarthakchats**
Fixes #14 
https://saarthakchats.github.io/geolocations/

### CODE REVIEW

**Comment by saarthakchats** [comment]
Oh okay, @abishekvashok. 
So what about this task? https://codein.withgoogle.com/tasks/6504849932812288/?sp-search=geoloca

**Comment by saarthakchats** [comment]
Done!

**Comment by abishekvashok** [comment]
Thanks

**Comment by saarthakchats** [comment]
@abishekvashok 👍

**Comment by liveHarshit** [comment]
Task link: https://codein.withgoogle.com/dashboard/task-instances/5722937693831168/

**Pull request merged**
