### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Baidya99**

### CODE REVIEW

**Comment by Baidya99** [comment]
@niccokunzmann Could you merge this too.

**Comment by m1guelpf** [comment]
@Baidya99 Done

**Comment by Baidya99** [comment]
@niccokunzmann  Will this be enough for the task: https://codein.withgoogle.com/dashboard/task-instances/4551131982200832/

**Comment by niccokunzmann** [comment]
@Baidya99 sure. Please have a look.

**Comment by Baidya99** [comment]
@niccokunzmann Thanks. I have submitted the task.

**Pull request merged**
